# Generated by Django 3.1.3 on 2020-11-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=50)),
                ('country_of_origin', models.CharField(max_length=50)),
            ],
        ),
    ]
